### ISSUE TITLE
Vendor ID and Product ID

### ISSUE THREAD

**Issue by qazero** [MAKERSUN99/MAUS#1]
I'm interested in purchasing one of these but what is displayed for the Vendor ID and Product ID when plugged into a PC?

**Comment by MAKERSUN99** [comment]
hi, MAUS board uses micronucleus firmware for V-USB.
See this well documented FAQ: https://github.com/micronucleus/micronucleus/blob/master/firmware/usbdrv/USB-ID-FAQ.txt

In fact, Vendor ID 0x16c0 and Product ID 0x27da

![Screenshot 2024-08-18 225026](https://github.com/user-attachments/assets/b8b9a8f6-bf81-4a5b-9d70-e8833e50231b)
